using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TaskApi.Controllers
{
    [ApiController]
    [Route("api/[controller]/{EmailId}")]
    public class TaskController:ControllerBase
    {
        //TaskId would be autoGenerated
        
        [HttpPost]
        public async Task<ActionResult> CreateClothName()
        {
            
        }
        //will get data using emailId & TaskId
        [HttpGet("{id:int}")]
        public async Task<ActionResult> GetAllTasks(int id)
        {
            
        }
        //will get data using emailId & TaskId
        [HttpPut("{id:int}")]
        public async Task<ActionResult>UpdateTaskInfo(int id,UserModel model)
        {
            
        }
    }
}