using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TaskApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class TaskController:ControllerBase
    {
        //TaskId would be autoGenerated
        
        [HttpPost]
        public async Task<ActionResult> CreateTask(TaskModel model)
        {
            
        }
        //will get data using emailId & TaskId
        [HttpGet("{id:int}")]
        public async Task<ActionResult> GetTaskById(int id)
        {
            
        }
        [HttpGet]
        public async Task<ActionResult> GetAllTask()
        {
            
        }
        //will get data using emailId & TaskId
        [HttpPut("{id:int}")]
        public async Task<ActionResult>UpdateTaskInfo(int id,TaskModel model)
        {
            
        }
    }
}