using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace TaskApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UserController : ControllerBase
    {
        //Id will be autogenerated
        //we will make username and password unique field
        [HttpPost("auth")]
        public async Task<ActionResult> CreateUser()
        {
            return Ok();
        }

        [HttpPost]
        public async Task<ActionResult> AuthenticateUser()
        {
            return Ok();
        }

        //can't change Id
        //will get data using emailId
        [HttpPut("{username}")]
        public async Task<ActionResult> UpdateUserInfo(string UserName)
        {
            return Ok();
        }
    }
}