using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace TaskApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class UserController : ControllerBase
    {
        //Id will be autogenerated
        //we will make username and password unique field
        [HttpPost]
        public async Task<ActionResult> CreateUser()
        {
            
        }
        //get user using EmailID
        [HttpGet]
        public async Task<ActionResult> GetUserByPassword()
        {
            
        }
        //can't change Id
        //will get data using emailId
        [HttpPut]
        public async Task<ActionResult>UpdateUserInfo()
        {
            
        }
    }
}
